            - name: tauri-build
  # You may pin to the exact commit or the version.
  # uses: JonasKruckenberg/tauri-build@406f9292d464c04add8c74e8ed1ed4105b91a20e
  uses: JonasKruckenberg/tauri-build@v1.0.3
  with:
    # Binary to use to build the application
    runner: # npm
    # Additional arguments for the build command
    args: # run tauri build
    # Path to the root of the project
    projectPath: # ./
    # The target triple to build against
    target: # windowns
          
