name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows

    steps:
    - name: tauri-build
    # You may pin to the exact commit or the version.
    # uses: JonasKruckenberg/tauri-build@406f9292d464c04add8c74e8ed1ed4105b91a20e
      uses: JonasKruckenberg/tauri-build@v1.0.3
      id: tauri-build
